version: "3"
services:
  backend:
    container_name: backend
    image: ghcr.io/int371-13-49-129/int371back:dev
    environment:
      - MYSQL_DATABASE=jaid_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=kamin124712
    networks:
      allnetwork:
        ipv4_address: 172.20.0.3
    depends_on:
      - cache
  cache:
    container_name: redis
    images: "redis:alpine"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    network:
      allnetwork:
        ipv4_address: 172.20.0.5
    ports:
      - "6379:6379"
networks:
  default:
    external:
      name: allnetwork
  allnetwork:
    external: true
