version: "3"
services:
  backend:
    container_name: backend
    image: ghcr.io/int371-13-49-129/int371back:dev
    environment:
      - MYSQL_DATABASE=jaid_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=kamin124712
    networks:
      allnetwork:
        ipv4_address: 172.20.0.3

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local

networks:
  default:
    external:
      name: allnetwork
  allnetwork:
    external: true
